apiVersion: networking.k8s.io/v1
   kind: Ingress
   metadata:
     name: ingress-for-customdomain-http
     namespace: $KUBERNETES_NAMESPACE
     annotations:
       kubernetes.io/ingress.class: "public-iks-k8s-nginx"
   spec:
     rules:
     - host: $CUSTOM_SUBDOMAIN
       http:
         paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: kubernetesnodeapp
               port:
                number: 3000